### ISSUE TITLE
Base models to be retired - text-davinci-003

### ISSUE THREAD

**Issue by praharshkpnous** [dennisfelczy/OpenAI_Document_Analyzer#1]
One of the pre-requisites, text-davinci-003 seems to be retired. It's not available anymore and the replacement gpt-35-turbo-instruct is also not available yet as of 8/8/23.
I set up the project and ran it without text-davinci-003 and got an issue when I tried uploading a document. After uploading a document, when I clicked the "Analyse with OpenAI..." button, I got an error that the file was not found. Looking at the path in the error message, I copied the file to the /test/ location, but still it is not able to find the file. I am trying to debug this from my end. Please let me know if I need to set something up differently.

**Comment by dennisfelczy** [comment]
Thanks for the hint, I removed the Davinci model from the options. As soon as the Instruct model is available I will add it.

The pdf file should normally land in the files subfolder of your project

**Comment by praharshkpnous** [comment]
Thank you very much!!

Could you also add some more how-to steps so that people who are new to the openai environment can also try out the code with ease? For example  if, how to add each of the needed models etc. Could be a bit more elaborated, it will be a blessing for many enthusiasts.

Best Regards,
Praharsh KP
________________________________

**Comment by dennisfelczy** [comment]
Got your point. However, I think there is already brilliant learning material available on that:
https://learn.microsoft.com/en-us/training/modules/explore-azure-openai/
