### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by praharshkpnous** [dennisfelczy/OpenAI_Document_Analyzer#2]
Hello!
I set up the project with miniconda. Upon the first run, it gave me the below error. 

File "/Users/praharshkp/Documents/Development/Azure OpenAI/conda/Analyzer/helperfunctions.py", line 200, in load_embeddings
    st.session_state.vs = FAISS.load_local("projects/"+st.session_state.project+"/faiss/"+st.session_state.vector_index_name, embeddings)
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

Looks like it's not able to find the json file name from
st.session_state.vector_index_name=ci(st.session_state.project,jsonfilename,uploaded_file.name,token_size)
this line of code. 

when I see the folder, I see a folder with the json name in there.

Please note, 
  I am running this in a mac, and VS Code to modify code
  I am very new to Python as well as Azure AI
  I am not sure how to debug this in VSCode, so mostly using print statements.

**Comment by dennisfelczy** [comment]
Hi,
could you print the variables, to check which of them was not set?
Maybe try to rerun again using the menu on the upper right corner.
